version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8888:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin_root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user_mysql
      MYSQL_PASSWORD: pass_mysql
    ports:
      - 33069:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
     - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./laravel:/var/www/html
    ports:
    - 9000:80
    networks:
     - laravel

networks:
  laravel:





