version: "3.8"

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ./laravel:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel_network
    depends_on:
      - mysql
    entrypoint: ./start.sh

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www
    networks:
      - laravel_network
    depends_on:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin_root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user_mysql
      MYSQL_PASSWORD: pass_mysql

    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  random_http:
    image: httpd:latest
    container_name: random_http
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge





